CREATE TABLE "speed" (
	"SPEED"	REAL NOT NULL,
	"STREET"	TEXT NOT NULL,
	"DIRECTION"	INTEGER NOT NULL,
	"LON"	REAL NOT NULL,
	"LAT"	REAL NOT NULL,
	"RADAR"	TEXT NOT NULL,
	"RADARNAME"	TEXT NOT NULL,
	"TIME"	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
